# Iterating through lists

In [6]:
things_to_iterate_over = [1, 2, 3, 4, 5]
for variable in things_to_iterate_over:
    print(variable)

1
2
3
4
5


In [5]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


#Vectorised operations with Numpy

In [10]:
vals = list(range(1000))

new_vals= vals.copy()
print(new_vals[:5])
for idx in range(1000):
    new_vals[idx] +=10

print(new_vals[:5])

[0, 1, 2, 3, 4]
[10, 11, 12, 13, 14]


In [12]:
import numpy as np

new_vals = np.array(vals)

new_vals += 10
new_vals[:5]

array([10, 11, 12, 13, 14])

In [15]:
%timeit
for idx in range(1000):
    vals[idx] + 10

In [17]:
#time to execute
%timeit new_vals + 10

1.52 µs ± 68.4 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Working with multiple dimensions

In [23]:
arr2d = np.arange(0, 40) # sequence of numbers from 0 to 39
arr2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [24]:
arr2d = arr2d.reshape([5, 8])  # reshape so it has 5 rows and 8 columns
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39]])